version: '3'
 
services:
    server:
        container_name: server
        restart: always
        build: .
        ports:
            - "80:3000" 
        links:
            - mongo
        environment:
            PORT: 3000
            DATABASE: "test"
            COLLECTION: "test"
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017" 
        command: "--smallfiles --logpath=/dev/null --quiet"
        volumes:
            - ../@db:/data/db
    
